### ISSUE TITLE
Structure of encryption Key / Invalid message authentication code

### ISSUE THREAD

**Issue by Dwarfex** [rkeet/zf-doctrine-encrypt#3]
Hi, 

unfortunately there are no exaples of keys / pepper in your config file. 
So i would expect i may use any 32 character string.

Encrypting with a key string like "012345678901234567890123456789ab" works. But decrypting doesn't. 

 I get an Exception "Invalid message authentication code" from /paragonie/halite/src/Symmetric/Crypto.php:191

Unfortunately i am not able to distinguish the real responsible package. Have you experienced something like this?
Hope you can help me. 

Callstack:

`#0 /vendor/paragonie/halite/src/Symmetric/Crypto.php(105): ParagonIE\Halite\Symmetric\Crypto::decryptWithAd('1B\x04\x00Q;\xAB\x8E\xBF<\xFD'\xFAF\xF3...', Object(ParagonIE\Halite\Symmetric\EncryptionKey), '', 'base64urlsafe')
#1 /vendor/rkeet/zf-doctrine-encrypt/src/Adapter/EncryptionAdapter.php(69): ParagonIE\Halite\Symmetric\Crypto::decrypt('MUIEAFE7q46_PP0...', Object(ParagonIE\Halite\Symmetric\EncryptionKey))
#2 /vendor/rkeet/zf-doctrine-encrypt/src/Subscriber/EncryptionSubscriber.php(226): Keet\Encrypt\Adapter\EncryptionAdapter->decrypt('MUIEAFE7q46_PP0...')
#3 /vendor/rkeet/zf-doctrine-encrypt/src/Subscriber/EncryptionSubscriber.php(176): Keet\Encrypt\Subscriber\EncryptionSubscriber->processFields(Object(Project\Entity\File), Object(Doctrine\ORM\EntityManager), false)
#4 /vendor/doctrine/event-manager/lib/Doctrine/Common/EventManager.php(40): Keet\Encrypt\Subscriber\EncryptionSubscriber->postLoad(Object(Doctrine\ORM\Event\LifecycleEventArgs))
#5 /vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php(117): Doctrine\Common\EventManager->dispatchEvent('postLoad', Object(Doctrine\ORM\Event\LifecycleEventArgs))
#6 /vendor/doctrine/orm/lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php(95): Doctrine\ORM\Event\ListenersInvoker->invoke(Object(Doctrine\ORM\Mapping\ClassMetadata), 'postLoad', Object(Project\Entity\File), Object(Doctrine\ORM\Event\LifecycleEventArgs), 4)
#7 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3564): Doctrine\ORM\Internal\HydrationCompleteHandler->hydrationComplete()
#8 /vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(57): Doctrine\ORM\UnitOfWork->hydrationComplete()
#9 /vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(154): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->cleanup()
#10 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(908): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(Object(Doctrine\DBAL\Driver\PDOStatement), Object(Doctrine\ORM\Query\ResultSetMapping), Array)
#11 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(181): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, NULL, NULL, NULL)
#12 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(164): Doctrine\ORM\EntityRepository->findBy(Array)
#13 /module/Project/src/Service/UserService.php(29): Doctrine\ORM\EntityRepository->findAll()
#14 /module/Project/src/Controller/DefaultController.php(39): Project\Service\UserService->getAllActiveUsers()
#15 /vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Project\Controller\DefaultController->indexAction()
#16 /vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(104): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#19 /vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 /vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#23 /public/index.php(40): Zend\Mvc\Application->run()
#24 {main}`

**Comment by rkeet** [comment]
Hi, did you have a look here: https://github.com/rkeet/zf-doctrine-encrypt/blob/master/config/local.config.php.dist ? 

If you copy over this config to a non-`.dist` file in your project, e.g. in your projects `local.php` and enter in the 32 character strings of your choosing, it should work out of the box. 

` i would expect i may use any 32 character string` -> correct

**Comment by Dwarfex** [comment]
Hi, yeah - i just found my mistake.

I used 
`/**
     * @ORM\Column(type="string", nullable=false)
     * @Encrypted
     * @var string
     */`
as annotation. Wich uses VARCHAR(255) and cuts the cypher after 255 chars.
I had to use "ORM\Column(type="text", nullable=false)" as the cypher is longer than 255 chars.

Now it's working. Maybe you could update this in the README file? 

This leads me to the question how this will be handled: 
` * @ORM\Column(name="house_number", type="integer", length=20, nullable=false)
    @Encrypted(type="int")`


Btw - big shoutout to you for your quick response time ;)

**Comment by rkeet** [comment]
> I had to use "ORM\Column(type="text", nullable=false)" as the cypher is longer than 255 chars.
> 
> Now it's working. Maybe you could update this in the README file?

Very good point. I see that in the README there is an example showing exactly what you did. Sorry about that. Will get on that asap, or could you open a PR with that change?

---

Handling the integer: 

> `@Encrypted(type="int")`

The Annotation is read by the Subscriber. If you [look here](https://github.com/rkeet/zf-doctrine-encrypt/blob/ee33abca341775fa457ce0faadcc7a22c50c1d5c/src/Subscriber/EncryptionSubscriber.php#L228) you'll see that it get's the given "type":

> `$type = $annotationOptions->getType();`

Followed [here](https://github.com/rkeet/zf-doctrine-encrypt/blob/ee33abca341775fa457ce0faadcc7a22c50c1d5c/src/Subscriber/EncryptionSubscriber.php#L251) by:

> `if (settype($value, $type) === false)`

If you look at the [definition of `settype`](https://www.php.net/manual/en/function.settype.php) on PHP.net, you see that it works by reference. (`settype ( mixed &$var , string $type ) : bool`). As such, right there the conversion back to the type registered in the Annotation is done. If it returns `false` (strict), then it failed conversion.

---

> Btw - big shoutout to you for your quick response time ;)

Thanks :) (this fast this time by chance though, happened to notice notification :p)

**Comment by Dwarfex** [comment]
Hmm.. 
Writing an Entity to the database with 
`/**
     * @ORM\Column(type="integer", length=20, nullable=false)
     * @Encrypted(type="int")
     * @var int
     */
    protected $filesize;`

results in a Field Value of "0"

`<?php
// $value is encrypted "Lorem Ipsum ...."
$value = 'MUIEAFnZqZfohM3jteizVjUn5hgYQp4fpBcIgxq8CktOBF_cZfZH4DuSpa_7NtbeXg9CtO72JmTRwAhHyo4LdTdHPAs0YAz7_5nN0mbDT7zhCOTVXRJnKuze_cs4Z0OBTjsNRND6hzTsx_L8CSTV-yxRtepOJ_x2daQ-4qJMi3vihxgBpJMvMJgkgbWuX_4sSGD4VY63THEZH8C3jlF3zLltwdE6G_HyA0gF99eqVW5chsSIBdBHSPhQ81NLUXsgNJV8G9Xkw3FjeANsmEmMdXbj-KbWdbuz76eniwa0PvSfVD6BQRx36Qxxvg6MYc4=';

$result = settype($value, 'int');
var_dump($result, $value);`

results in 
`bool(true)
int(0)
`

So it seems i have to use a text field too.

**Comment by rkeet** [comment]
Yes that is indeed the case, sorry if that wasn't clear in my previous comment. Anything that gets encrypted will exceed the 255 char limit. It's also always a string, so `type="integer", length=20` would always fail. 

As such, you'd always need `@ORM\Column(type="text")` (possibly `nullable=false` if you require it)

Would like it if you could create a PR to update the docs for this. Else I'll get on that soonest (should be this week).
