### ISSUE TITLE
Laminas Compatibility

### ISSUE THREAD

**Issue by Dwarfex** [rkeet/zf-doctrine-encrypt#6]
Hi :)
first of all thanks for your work!

As ZendFramework is now Laminas - what about a new version of your package with Laminas compatibility?

Greetings,
Dwarfex

**Comment by rkeet** [comment]
Hi Dwarfex,

Thanks for the heads up on Laminas. 

I've marked all ZF repo's as abandoned as I've not had the time or will to work on them. I've been pursuing different things. 

Feel free to fork and update the project. If you wish, I could also set your fork as the recommended, though would suggest you incorporate [this fix](https://github.com/rkeet/zf-doctrine-encrypt/pull/5#issuecomment-547291184) as well if you do ;) 

Thanks for your interest!

**Comment by Dwarfex** [comment]
Hi @rkeet, 
thank you for your clarification. 
I forked this project under the name "somecoding/laminas-doctrine-encrypt" and added the small fix.

Good luck & have fun on new projects!
